In [2]:
import pandas as pd
mpg = pd.read_csv('mpg.csv')
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

### 1. displ 4 이하인 자동차와 5 이상인 자동차 hwy의 평균 비교

In [5]:
displ_1 = mpg.query('displ <= 4')

In [6]:
displ_2 = mpg.query('displ >= 5')

In [8]:
displ_1['hwy'].mean()

np.float64(25.96319018404908)

In [9]:
displ_2['hwy'].mean()

np.float64(18.07894736842105)

displ_1['hwy'].mean()가 displ_2['hwy'].mean() 보다 높다.
따라서, 배기량이 4 이하인 자동차의 고속도로 연비 평균이 더 높다.

### 2. audi 와 toyota 중 어느 자동차 제조 회사의 도시 연비 평균이 더 높은가

In [14]:
audi_m = mpg.query('manufacturer == "audi"')

In [15]:
toyota_m = mpg.query('manufacturer == "toyota"')

In [17]:
audi_m['cty'].mean()

np.float64(17.61111111111111)

In [18]:
toyota_m['cty'].mean()

np.float64(18.529411764705884)

toyota_m['cty'].mean()가 audi_m['cty'].mean()보다 높다. 따라서 toyota의 도시 연비 평균이 더 높다.

### 3. category, cty를 추출해 mpg_new를 만들고 head()를 이용해 출력하라.

In [19]:
mpg_new = mpg[['category', 'cty']]

In [20]:
mpg_new.head()

  category  cty
0  compact   18
1  compact   21
2  compact   20
3  compact   21
4  compact   16

mpg_new의 출력 결과는 위와 같다.

### 4. 3